### ISSUE TITLE
Create Task 1 Project presentation

### ISSUE THREAD

**Issue by konkalo** [Jacarte/MF240VHT211#4]

**Comment by Jacarte** [comment]
Full report from ESET, including code, diagrams, dissection of the malware. https://www.welivesecurity.com/wp-content/uploads/2017/06/Win32_Industroyer.pdf

Some links:
- [Lack of security on the protocols...](https://ieeexplore.ieee.org/abstract/document/9507115?casa_token=xlZLKtbfrFsAAAAA:Xrf4bn7eB1VoTtDfmALIbDWqh4Od8PJOMsS3qCuynFTiSj0Es3A3dHQNkMgk20XIPADVLenwvA )
- [Report from ESET: Industroyer: ICS protocols were developed decades ago with no security in mind](https://www.welivesecurity.com/2017/06/19/industroyer-interview-ics-developed-decades-ago-no-security-mind/)
- [The Industroyer Malware, also known as Crash Override, Is Stuxnet’s Successor](https://bestsecuritysearch.com/industroyer-malware-also-known-crash-override-stuxnets-successor/)

**Comment by Jacarte** [comment]
Slides

https://docs.google.com/presentation/d/1skjjvzSFE7tap1mT8uATthtAmucJwlGfFym3DZ05954/edit?usp=sharing
